package URL.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.cells.EditorCell;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.editor.runtime.cells.AbstractCellAction;
import BrowserPlugin.plugin.BrowserPlugin;

public class CallBrowser {
  public static void setCellActions(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.setAction(CellActionType.CLICK, new CallBrowser.CallBrowser_CLICK(node));
  }
  public static class CallBrowser_CLICK extends AbstractCellAction {
    /*package*/ SNode myNode;
    public CallBrowser_CLICK(SNode node) {
      this.myNode = node;
    }
    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }
    public void execute_internal(EditorContext editorContext, SNode node) {
      BrowserPlugin browserPlugin = new BrowserPlugin();
      browserPlugin.load(node);
    }
  }
}
