package URL.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.cells.EditorCell;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.editor.runtime.cells.AbstractCellAction;
import BrowserPlugin.plugin.BrowserPlugin;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class OpenBrowser {
  public static void setCellActions(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.setAction(CellActionType.CLICK, new OpenBrowser.OpenBrowser_CLICK(node));
  }
  public static class OpenBrowser_CLICK extends AbstractCellAction {
    /*package*/ SNode myNode;
    public OpenBrowser_CLICK(SNode node) {
      this.myNode = node;
    }
    public String getDescriptionText() {
      return "Open browser";
    }
    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }
    public void execute_internal(EditorContext editorContext, SNode node) {
      BrowserPlugin browserPlugin = new BrowserPlugin();
      System.out.println("Call load url " + SPropertyOperations.getString(node, MetaAdapterFactory.getProperty(0xc6a53bd096274db5L, 0xb62adbc3d020d641L, 0x3e37d3fcba83a53dL, 0x767b1c753675469L, "url")));
      browserPlugin.load(node);
    }
  }
}
