package URL.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int BWBNummer = 0;
  public static final int Context = 1;
  public static final int JCKey = 2;
  public static final int JCKeyValuePaar = 3;
  public static final int JCType = 4;
  public static final int JCTypeC = 5;
  public static final int JCTypeV = 6;
  public static final int JCValue = 7;
  public static final int Link = 8;
  public static final int URL = 9;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xc6a53bd096274db5L, 0xb62adbc3d020d641L);
    builder.put(0x767b1c753675565L, BWBNummer);
    builder.put(0x767b1c753675588L, Context);
    builder.put(0x767b1c753675586L, JCKey);
    builder.put(0x767b1c753675585L, JCKeyValuePaar);
    builder.put(0x767b1c75367550cL, JCType);
    builder.put(0x767b1c75367550dL, JCTypeC);
    builder.put(0x767b1c75367551cL, JCTypeV);
    builder.put(0x767b1c753675587L, JCValue);
    builder.put(0x767b1c75367546cL, Link);
    builder.put(0x3e37d3fcba83a53dL, URL);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
