package BrowserPlugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.tool.GeneratedTool;
import javax.swing.Icon;
import com.intellij.openapi.project.Project;
import javax.swing.JPanel;
import JavaFXBrowser.SwingFXWebView;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import javax.swing.KeyStroke;
import java.util.HashMap;
import com.intellij.openapi.wm.ToolWindowAnchor;
import java.awt.BorderLayout;
import java.awt.Component;
import jetbrains.mps.ide.ThreadUtils;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import javax.swing.JComponent;

public class BrowserTool_Tool extends GeneratedTool {
  private static final Icon ICON = null;
  private Project projectvar;
  private JPanel jp;
  private SwingFXWebView fxWebView;
  public BrowserTool_Tool(Project project) {
    super(project, "Wetten.nl", MapSequence.<String, KeyStroke>fromMapAndKeysArray(new HashMap<String, KeyStroke>(), "Mac OS X").withValues(KeyStroke.getKeyStroke("alt shift 2")), ICON, ToolWindowAnchor.BOTTOM, false);
  }
  public void init(Project project) {
    super.init(project);
    Runnable r = new Runnable() {
      public void run() {
        BrowserTool_Tool.this.projectvar = project;
        BrowserTool_Tool.this.jp = new JPanel(new BorderLayout());
        BrowserTool_Tool.this.jp.add(new SwingFXWebView());
        for (Component component : BrowserTool_Tool.this.jp.getComponents()) {
          if (component instanceof SwingFXWebView) {
            BrowserTool_Tool.this.fxWebView = (SwingFXWebView) component;
            BrowserTool_Tool.this.fxWebView.setCurrentURL("http://wetten.overheid.nl/jci1.3:c:BWBR0011173&artikel=1&z=2000-07-01&g=2000-07-01");
            BrowserTool_Tool.this.fxWebView.load();
          }
        }
        BrowserTool_Tool.this.makeAvailable();
      }
    };
    ThreadUtils.runInUIThreadNoWait(r);

  }
  public void load(SNode url) {
    BrowserTool_Tool.this.fxWebView.setCurrentURL(SPropertyOperations.getString(url, MetaAdapterFactory.getProperty(0xc6a53bd096274db5L, 0xb62adbc3d020d641L, 0x3e37d3fcba83a53dL, 0x767b1c753675469L, "url")));
    BrowserTool_Tool.this.fxWebView.load();
  }
  public JComponent getComponent() {
    return BrowserTool_Tool.this.jp;
  }
}
