package BrowserPlugin.plugin;

/*Generated by MPS */

import com.intellij.openapi.project.Project;
import org.jetbrains.mps.openapi.model.SNode;

public class BrowserPlugin {
  private static Project project;
  private static BrowserTool_Tool browsertool;

  public BrowserPlugin() {
  }
  public BrowserPlugin(Project mpsProject, BrowserTool_Tool tool) {
    project = mpsProject;
    browsertool = tool;
  }
  public void load(SNode url) {
    browsertool.load(url);
  }
}
