package BrowserPlugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.tool.GeneratedTool;
import javax.swing.Icon;
import com.intellij.openapi.project.Project;
import javax.swing.JPanel;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import javax.swing.KeyStroke;
import java.util.HashMap;
import com.intellij.openapi.wm.ToolWindowAnchor;
import java.awt.BorderLayout;
import javax.swing.JComponent;

public class Browser_Tool extends GeneratedTool {
  private static final Icon ICON = null;
  private Project projectvar;
  private JPanel jp;
  public Browser_Tool(Project project) {
    super(project, "Browser", MapSequence.<String, KeyStroke>fromMapAndKeysArray(new HashMap<String, KeyStroke>(), "Mac OS X").withValues(KeyStroke.getKeyStroke("alt shift 2")), ICON, ToolWindowAnchor.BOTTOM, false);
  }
  public void init(Project project) {
    super.init(project);
    Browser_Tool.this.projectvar = project;
    Browser_Tool.this.jp = new JPanel(new BorderLayout());
    Browser_Tool.this.makeAvailable();
  }
  public JComponent getComponent() {
    return Browser_Tool.this.jp;
  }
}
