package BrowserPlugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.applicationplugins.BaseApplicationPlugin;
import com.intellij.openapi.extensions.PluginId;
import jetbrains.mps.ide.actions.SolutionActions_ActionGroup;

public class BrowserPlugin_ApplicationPlugin extends BaseApplicationPlugin {
  private PluginId myId = PluginId.getId("BrowserPlugin");
  public BrowserPlugin_ApplicationPlugin() {
  }
  public PluginId getId() {
    return myId;
  }
  public void createGroups() {
    // actions w/o parameters 
    addAction(new Browser_Action());
    // groups 
    addGroup(new Browser_ActionGroup());
  }
  public void adjustRegularGroups() {
    insertGroupIntoAnother(Browser_ActionGroup.ID, SolutionActions_ActionGroup.ID, null);
  }
}
