package BrowserPlugin.plugin;

/*Generated by MPS */

import jetbrains.mps.workbench.action.BaseAction;
import javax.swing.Icon;
import org.jetbrains.annotations.NotNull;
import com.intellij.openapi.actionSystem.AnActionEvent;
import java.util.Map;
import jetbrains.mps.plugins.projectplugins.ProjectPluginManager;

public class null_Action extends BaseAction {
  private static final Icon ICON = null;

  public null_Action() {
    super("", "", ICON);
    this.setIsAlwaysVisible(false);
    this.setExecuteOutsideCommand(false);
  }
  @Override
  public boolean isDumbAware() {
    return true;
  }
  @Override
  public void doExecute(@NotNull final AnActionEvent event, final Map<String, Object> _params) {
    event.getProject().getComponent(ProjectPluginManager.class).getTool(Browser_Tool.class).fxWebView;
  }
}
