package BrowserPlugin.plugin;

/*Generated by MPS */

import javax.swing.JPanel;
import javafx.stage.Stage;
import javafx.scene.web.WebView;
import javafx.embed.swing.JFXPanel;
import javax.swing.JButton;
import javafx.scene.web.WebEngine;
import javax.swing.SwingUtilities;
import javax.swing.JFrame;
import java.awt.Dimension;
import java.awt.BorderLayout;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javafx.application.Platform;
import com.sun.javafx.application.PlatformImpl;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.collections.ObservableList;
import javafx.scene.Node;

public class SwingFXWebView extends JPanel {
  private Stage stage;
  private WebView browser;
  private JFXPanel jfxPanel;
  private JButton swingButton;
  private WebEngine webEngine;
  public SwingFXWebView() {
    initComponents();
  }
  public static void main(String... args) {
    // Run this later: 
    SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        final JFrame frame = new JFrame();
        frame.getContentPane().add(new SwingFXWebView());
        frame.setMinimumSize(new Dimension(640, 480));
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
      }
    });
  }
  public void run() {
    final JFrame frame = new JFrame();
    frame.getContentPane().add(new SwingFXWebView());
    frame.setMinimumSize(new Dimension(640, 480));
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.setVisible(true);
  }
  private void initComponents() {
    jfxPanel = new JFXPanel();
    createScene();
    setLayout(new BorderLayout());
    add(jfxPanel, BorderLayout.CENTER);
    swingButton = new JButton();
    swingButton.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        Platform.runLater(new Runnable() {
          @Override
          public void run() {
            webEngine.reload();
          }
        });
      }
    });
    swingButton.setText("Reload");
    add(swingButton, BorderLayout.SOUTH);
  }
  /**
   *  createScene 
   * 
   *  Note: Key is that Scene needs to be created and run on "FX user thread" 
   *        NOT on the AWT-EventQueue Thread 
   * 
   */
  private void createScene() {
    PlatformImpl.startup(new Runnable() {
      @Override
      public void run() {
        stage = new Stage();
        stage.setTitle("Hello Java FX");
        stage.setResizable(true);
        Group root = new Group();
        Scene scene = new Scene(root, 80, 20);
        stage.setScene(scene);
        // Set up the embedded browser: 
        browser = new WebView();
        webEngine = browser.getEngine();
        webEngine.load("http://www.wetten.nl");
        ObservableList<Node> children = root.getChildren();
        children.add(browser);
        jfxPanel.setScene(scene);
      }
    });
  }
  public void load(String url) {
    webEngine.load(url);
  }

}
